# Numpy Basics

In [1]:
import numpy as np

li_array = [x for x in range(0,100)]
np_array = np.arange(100)
print(li_array)
print(np_array)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
print(np_array.itemsize)
print(np_array.itemsize * np_array.size)

4
400


In [3]:
import sys
a = 10 

#size of one element in the list
print(sys.getsizeof(a))

# size of 100 elements i list
print(sys.getsizeof(1)*len(li_array))

28
2800


In [4]:
import time 
import numpy as np

size = 100000

# add elements of array a and b
def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i]+b[i] for i in range(size)]
    t2 = time.time()
    return (t2-t1)
def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return (t2-t1)
t_list = addition_using_list()
t_numpy = addition_using_numpy()
print("List=", t_list * 1000)  ##milliseconds
print("numpy=",t_numpy *1000) ##milliseconds

List= 55.753231048583984
numpy= 2.5746822357177734


In [5]:
a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
a = [1,2,3,4,'5',24]
b = np.array(a,dtype=int)
print(b)

[ 1  2  3  4  5 24]


In [7]:
b = np.array(a*3,dtype=int)
print(b)

[ 1  2  3  4  5 24  1  2  3  4  5 24  1  2  3  4  5 24]


In [8]:
b = np.ones(3,dtype=int)
c = np.ones((2,4),dtype=int)
d = np.zeros(5,dtype=int)
e = np.zeros((4,5),dtype=int)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)

b: [1 1 1]
c: [[1 1 1 1]
 [1 1 1 1]]
d: [0 0 0 0 0]
e: [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
b = np.full(3,5,dtype=float)
c = np.full((3,3),8)
print(b)
print(c)

[5. 5. 5.]
[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [10]:
a =np.empty((3,4))
print(a)

[[1.04887161e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.08221785e-312 1.00392456e-042 9.96389841e-043 6.58024818e-038]
 [8.45045576e+169 1.56300348e+185 1.10632629e+165 4.27605152e-037]]


In [11]:
a = np.arange(10)
print(a)
b = np.arange(5,20)
print(b)
c = np.arange(6,21,3)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
#for this the third value that is the num which is by default the 50 so it generated the 50 values which are evenly spaced from 2 to 10
a= np.linspace(2,10)
print(a)
b = np.linspace(2,20,5,dtype=int,endpoint=False) # for this start is 2 end is 20 and generates the 5 values 
print(b)

[ 2.          2.16326531  2.32653061  2.48979592  2.65306122  2.81632653
  2.97959184  3.14285714  3.30612245  3.46938776  3.63265306  3.79591837
  3.95918367  4.12244898  4.28571429  4.44897959  4.6122449   4.7755102
  4.93877551  5.10204082  5.26530612  5.42857143  5.59183673  5.75510204
  5.91836735  6.08163265  6.24489796  6.40816327  6.57142857  6.73469388
  6.89795918  7.06122449  7.2244898   7.3877551   7.55102041  7.71428571
  7.87755102  8.04081633  8.20408163  8.36734694  8.53061224  8.69387755
  8.85714286  9.02040816  9.18367347  9.34693878  9.51020408  9.67346939
  9.83673469 10.        ]
[ 2  5  9 12 16]


In [13]:
a = np.identity(3,dtype=int)
print(a)
b= np.eye(3)
print(b)
c = np.eye(3,4)
print(c)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [14]:
b = np.random.rand(3)
print(b)
c = np.random.rand(3,5)
print(c)

[0.49735143 0.30991999 0.70054435]
[[0.81095028 0.3398283  0.46535744 0.24809389 0.53613226]
 [0.22686685 0.4181249  0.94504857 0.92144302 0.07684034]
 [0.3609785  0.44964554 0.04503532 0.7357794  0.37699852]]


In [15]:
a = np.random.rand(10)*10
print(a)

[3.79259081 8.92689319 1.64379106 2.61344027 1.54976064 7.01221136
 2.28729386 4.12956574 8.57488132 2.32509737]


In [16]:
a =np.random.randint(2)
print(a)

0


In [17]:
a = [1,2,3,4,5]
arr = np.array(a)
print(arr)
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides) 

[1 2 3 4 5]
(5,)
int32
(4,)


In [18]:
a = [[1,2,3,4],[3,4,5,6],[7,8,9,5],[1,2,3,4]]
arr = np.array(a)
print(arr)
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)
print(arr[1,:3])
print(arr[0:3,2])
print(arr[2:4,1:3])

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 5]
 [1 2 3 4]]
(4, 4)
int32
(16, 4)
[3 4 5]
[3 5 9]
[[8 9]
 [2 3]]


In [19]:
a = [1,2,3,4]
arr = np.array(a)
print(arr[1:3])

[2 3]


In [20]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[18  7  2  3 10]
[ 4 12  8 15 15]


In [21]:
li = [i+1 for i in li]
print(li)

[2, 3, 4, 5, 6]


In [23]:
a = a+1
print(a)
c = a+b
print(c)

[19  8  3  4 11]
[23 20 11 19 26]


In [24]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)

[23 20 11 19 26]
[ 15  -4  -5 -11  -4]
[ 76  96  24  60 165]
[4.75       0.66666667 0.375      0.26666667 0.73333333]
[4 0 0 0 0]
[    130321          0       6561 1073741824 1632031715]


In [25]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

45
9.0
3
19
2
0


In [26]:
print(a>b)
print(a<b)
print(a==b)

[ True False False False False]
[False  True  True  True  True]
[False False False False False]


In [27]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))
print(np.logical_not(b))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]
[False False False False False]


In [28]:
a[2] = 0
print(a)
print(np.logical_not(a))

[19  8  0  4 11]
[False False  True False False]


In [29]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[16  4 19 15 11 19 17  3]


In [30]:
print(b > 10)

[ True False  True  True  True  True  True False]


In [31]:
bool_arr = b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False  True  True  True  True  True False]
[16 19 15 11 19 17]


In [32]:
new_arr = b[b>10]
print(new_arr)

[16 19 15 11 19 17]


In [33]:
new_arr = b[(b>10) & (b<18)]
print(new_arr)

[16 15 11 17]


In [34]:
c = b
print(c)

[16  4 19 15 11 19 17  3]


In [35]:
c[:3] = 19
print(c)
c[c>15] = 100
print(c)

[19 19 19 15 11 19 17  3]
[100 100 100  15  11 100 100   3]


In [36]:
print(b)

[100 100 100  15  11 100 100   3]


In [37]:
print(b[b == 100])

[100 100 100 100 100]


In [38]:
ind = np.where(b == 100)
print(ind)
print(a)
print(a[ind])

(array([0, 1, 2, 5, 6], dtype=int64),)
['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
['t' 'b' 'r' 'f' 'z']


In [39]:
a= np.random.randint(1,30,(5,6))
print(a)
print(a>20)
print(a[a>20])
new_arr = np.where(a>20)
print(new_arr)

[[13  4 13 25  9 10]
 [ 7 17 25 28 17 10]
 [ 4  1 10  5 28 20]
 [ 1 20 16 20 14 23]
 [27 14 24  4  5 22]]
[[False False False  True False False]
 [False False  True  True False False]
 [False False False False  True False]
 [False False False False False  True]
 [ True False  True False False  True]]
[25 25 28 28 23 27 24 22]
(array([0, 1, 1, 2, 3, 4, 4, 4], dtype=int64), array([3, 2, 3, 4, 5, 0, 2, 5], dtype=int64))


In [40]:
b = a
print(b)
bool_arr = b>20
print(bool_arr)
b[bool_arr] = 100
print(b)

[[13  4 13 25  9 10]
 [ 7 17 25 28 17 10]
 [ 4  1 10  5 28 20]
 [ 1 20 16 20 14 23]
 [27 14 24  4  5 22]]
[[False False False  True False False]
 [False False  True  True False False]
 [False False False False  True False]
 [False False False False False  True]
 [ True False  True False False  True]]
[[ 13   4  13 100   9  10]
 [  7  17 100 100  17  10]
 [  4   1  10   5 100  20]
 [  1  20  16  20  14 100]
 [100  14 100   4   5 100]]


In [41]:
c = np.random.randint(1,10,(2,2))
print(c)
c_bool = np.array([[True,False],[False,True],[True,False]])
print(c_bool)

[[5 5]
 [4 4]]
[[ True False]
 [False  True]
 [ True False]]


In [42]:
print(b)
bool_arr = b[:,3] == 100
print(bool_arr)

[[ 13   4  13 100   9  10]
 [  7  17 100 100  17  10]
 [  4   1  10   5 100  20]
 [  1  20  16  20  14 100]
 [100  14 100   4   5 100]]
[ True  True False False False]


In [43]:
b[bool_arr,3] = 99
print(b)

[[ 13   4  13  99   9  10]
 [  7  17 100  99  17  10]
 [  4   1  10   5 100  20]
 [  1  20  16  20  14 100]
 [100  14 100   4   5 100]]


In [44]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print("x:",x)
print("y:",y)
print("x+y:",x+y)
print("x-y:",x-y)
print("x*y:",x*y)

x: [[9 1 3]
 [6 2 9]
 [7 7 3]]
y: [6 8 4]
x+y: [[15  9  7]
 [12 10 13]
 [13 15  7]]
x-y: [[ 3 -7 -1]
 [ 0 -6  5]
 [ 1 -1 -1]]
x*y: [[54  8 12]
 [36 16 36]
 [42 56 12]]


In [45]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
print(x)
print(y)
x=np.transpose(x)
print(x)
print(x+y)

[[9 4]
 [2 6]
 [2 4]]
[[4 1 7]
 [4 8 2]]
[[9 2 2]
 [4 6 4]]
[[13  3  9]
 [ 8 14  6]]
